services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ba\Rest\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Dto,Exception,RestBundle.php}'

  Ba\Rest\ParamConverter\MapperConverter:
    tags:
      - { name: request.param_converter, priority: -2, converter: mapper_converter }

  Knp\Component\Pager\Event\Subscriber\Paginate\PaginationSubscriber: ~
  Knp\Component\Pager\PaginatorInterface:
    class: Knp\Component\Pager\Paginator
    arguments:
    - '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'

